name: SwishhyysAdditions
version: '0.0.1'
main: me.swishhyy.swishhyysAdditions.SwishhyysAdditions
api-version: '1.21.4'
authors: [ Swishhyy ]
softdepend:
  - HeadDatabase

commands:
  gcrystal:
    description: Gives you a Growing Crystal
    usage: /gcrystal

